### PR TITLE
Fix error logging for standalone module

### LINKED ISSUE #3373: Standalone module no longer logs client IP to error log
**Describe the bug**

The 2.9.8 release introduced a bug for the "standalone module" version of ModSecurity v2 whereby the client source IP address is no longer written to the error log.

This is a very big problem as it is common to rely on the error log output for the purposes of monitoring, resolving false positives, identifying attacks, producing statistics / reports / dashboards, and more. Without the client's IP address in the error logs these tasks become impossible.

This bug was introduced in PR #3192 during an effort to tidy error logging in v2 for Apache. The format strings that control error logging [were altered](https://github.com/owasp-modsecurity/ModSecurity/pull/3192/files#diff-f7042e3212265ddbdf32d44c0fca670fbe6d8be64f688aa7dead0c25151c0669L288) to remove the explicit `[client %s]` output at the start of the log line. It seems that Apache will implicitly write this source IP information, making it redundant for ModSecurity to add. A *standalone* (Apache-less) compilation of ModSecurity **requires** the `[client %s]` information to be explicitly written to the error log as Apache is not present to implicitly write it.

**Logs and dumps**

Error log examples:

##### Before updating to ModSecurity 2.9.8:

`2025-05-06T17:02:29+00:00 loadbalancer wafservice: [client 192.168.1.131] ModSecurity: Warning. Matched phrase "bin/bash" at ARGS:exec...`

##### After updating to ModSecurity 2.9.8:

`2025-05-06T15:46:11+00:00 loadbalancer wafservice: ModSecurity: Warning. Matched phrase "bin/bash" at ARGS:exec. [file "/waf/3/REQ...`

Notice that the `[client 192.168.1.131]` section is now gone. The client source IP address is no longer written to the error log at all.

**To Reproduce**

Compile ModSecurity v2.9.8 in standalone mode, trigger a rule, and observe that the source IP address of the client is omitted.

**Expected behaviour**

The client source IP address must always be written to the error log.

**Server:**

 - ModSecurity v2.9.8, standalone mode
 - WebServer: n/a
 - OS (and distro): Debian

**Rule Set (please complete the following information):**
 - OWASP CRS v3.3.7

### PR DESCRIPTION
**Pull request by RedXanadu**
## what

This PR:

- Restores the original format string for error logging for ModSecurity _when compiled as a standalone module_.
- The format string has the explicit `[client %s]` back again: this is required for standalone modules as Apache is not present to implicitly log the client source IP address.
- The fix is achieved by adding conditional compilation directives so that for standalone mode the old error logging format strings are used.

## why

It is essential for the client source IP address to be written to the error log. This is required for resolving false positives, monitoring, detecting attacks, and the majority of day to day WAF operations.

This PR fixes the bug introduced in an attempt to tidy error logging for Apache in PR #3192.

## references

closes #3373

### CODE REVIEW

**Comment by RedXanadu** [comment]
I have tested this on a standalone installation of ModSecurity v2.9.8 and can confirm that it restores client IP address logging as intended.

**Comment by airween** [comment]
A reminder to me (or to us :smile:) - we should add more tests, eg. which will check standalone build (and test it...?) too.

File: apache2/apache2_util.c [hunk 1]
```diff
@@ -284,12 +284,27 @@ static void internal_log_ex(request_rec *r, directory_config *dcfg, modsec_rec *
...
+/* Standalone module must use original format string for logging with explicit
+ * "[client %s]" to log client IP address (no Apache to implicitly add this) */
+#else
+  #if AP_SERVER_MAJORVERSION_NUMBER > 1 && AP_SERVER_MINORVERSION_NUMBER > 2
+	ap_log_rerror(APLOG_MARK, APLOG_ERR | APLOG_NOERRNO, 0, r,
+            "[client %s] ModSecurity: %s%s [uri \"%s\"]%s", r->useragent_ip ? r->useragent_ip : r->connection->client_ip, str1,
+            hostname, log_escape(msr->mp, r->uri), unique_id);
+  #else
+        ap_log_error(APLOG_MARK, APLOG_ERR | APLOG_NOERRNO, 0, r->server,
+                "[client %s] ModSecurity: %s%s [uri \"%s\"]%s", msr->remote_addr ? msr->remote_addr : r->connection->remote_ip, str1,
```
Comment (airween) [inline apache2/apache2_util.c]: Just for the better visibility, could you use here the same indent (and below in line [306](https://github.com/owasp-modsecurity/ModSecurity/pull/3374/files#diff-f7042e3212265ddbdf32d44c0fca670fbe6d8be64f688aa7dead0c25151c0669R306) as in line [301/302](https://github.com/owasp-modsecurity/ModSecurity/pull/3374/files#diff-f7042e3212265ddbdf32d44c0fca670fbe6d8be64f688aa7dead0c25151c0669R301)?

**Review by airween — DISMISSED** [review]

File: apache2/apache2_util.c (hunk 1 above)
Comment (RedXanadu) [reply apache2/apache2_util.c]: Thanks, well spotted. Indentation is now fixed.

**Comment by airween** [comment]
Thanks @RedXanadu,

my last request: could you pick up the current state from `v2/master` and rebase your tree? I've added some new tests. Thanks!

**Comment by RedXanadu** [comment]
@airween Sure: now rebased onto the current `v2/master`.

**Comment by airween** [comment]
> @airween Sure: now rebased onto the current `v2/master`.

Awesome, thank you!

**Review by airween — APPROVED** [review]
LGTM
