### PR TITLE
fix: integer type limits, 2nd try

### LINKED ISSUE #3352: curl with PUT method can upload a huge file (>2GB) on remote server but hangs and timeout
**Describe the bug**
When we want to upload a huge file (>2GB) to a remote web site (Artifactory in our case) , our http client hangs indefinitely.
However, the file is correctly uploaded to Artifactory.

**Logs and dumps**
Output of:
 1. DebugLogs (level 9), cf attachments
 2. AuditLogs : this file is empty
 3. Error logs : 

**To Reproduce**
On a GNU/Linux machine do : 
```bash
dd if=/dev/urandom of=/tmp/2G.txt bs=1M count=2048
curl -u <myuser>:<my_api_key> -T /tmp/2G.txt 'https://artifactory.local/artifactory/generic/perf_debug/2G.txt
```
Then, the `curl`hangs.

**Expected behavior**
`curl` ends whithout error.

**Server :**
 - ModSecurity version (and connector): `ModSecurity` `v3.0.12` and `3.0.14` with `nginx-connector` `v1.0.3`
 - WebServer: `nginx-1.18.0`
 - OS: `GNU/Linux`, `Ubuntu 22.04`

**Rule Set (please complete the following information):**
 - Running any public or commercial rule set? [Core Security Rules](https://github.com/coreruleset/coreruleset), version `4.5.0`

**Additional context**

* The infrastructure is made like : `client -> haproxy -> nginx(+ modesec) -> Artifactory`
* More than the file size , the time to upload is more than 250 seconds when the upload fails
* The problem persists when we disable `Core Security Rules` usage
* The only way to avoid the problem is to set `modsecurity off;` in my vhost configuration
* Artifactory return a `HTTP 201`
* HTTP method used is `PUT`
* strace -> see attachments
* TCP segment missing when modsec is enabled (on nginx machine, interface connected to haproxy machine) : 
```
69719  272.819868  172.16.3.13  172.16.3.12  TCP  66  443 → 36912 [FIN, ACK] Seq=6734 Ack=2104577102 Win=2021120 Len=0 TSval=55543961 TSecr=2937796858
```
**Attachments:**
- [2000m_debug.log](https://github.com/user-attachments/files/19294975/2000m_debug.log)
- [final_strace.log](https://github.com/user-attachments/files/19295097/final_strace.log)

### PR DESCRIPTION
**Pull request by airween**
## what

This PR fixes the handling of integer type limits, eg. `SecRequestBodyNoFilesLimit`.

**Changes**:
* in `headers/modsecurity/rules_set_properties.h` I implemented a new template with name `ConfigValue`
* this implements the `parse()` method which reads safely the integer value from a string, which parsed by engine's SecLang parser (Bison)
* the template also sets the default `min` and `max` value to `0`
* this method checks the type limits, eg. if the type (for eg. `ConfigInt`) implements `int32_t` (`signed int` on AMD64), then the min and max limits will be -2147483648 and +2147483647
  * if you take a look at this minimum value, it can be familiar with the mentioned log message in [#3356](https://github.com/owasp-modsecurity/ModSecurity/issues/3356#issue-2959545090): `Request body excluding files is bigger than the maximum expected. Limit: -2147483648.000000`; the reason is (I write that below too) that the current implementation uses `atoi()` function, which converts a `string` to `signed int`, but if the value is bigger than the max value above, then it overflows and casts to `int`'s minimum
* out-of-bounds values will trigger an error at startup with a message in error.log
* with help of this template I implemented three types: `ConfigInt` (`int32_t`), `ConfigUnsignedInt` (`uint32_t`) and `ConfigUnsignedLong` (`uint64_t`)
* it's enough to set the min and max values in all new types (eg. if we want to add new integer types) - see existing new types; I used `std::numeric_limits<T>::min()` and `std::numeric_limits<T>::max()`
* I changed the type of variables: `m_argumentsLimit`, `m_requestBodyJsonDepthLimit`, `m_requestBodyLimit`, `m_requestBodyNoFilesLimit`, `m_responseBodyLimit`, `m_pcreMatchLimit`, `m_uploadFileLimit` and `m_uploadFileMode`;  the current types are [here](https://github.com/owasp-modsecurity/ModSecurity/blob/cf24aeaeadefd758d0220e485bd8e312945f06df/headers/modsecurity/rules_set_properties.h#L507-L514); now there is no more `ConfigDouble` type variable
* in `src/parser/seclang-parser.yy` I changed the type in grammar parser; there you can see the error handling (detailed error messages are in template's `parse()` method)
* I also regenerated `src/parser/seclang-parser.cc` (it's a generated file by Bison, don't need to check it)

**Other changes**:
* I fixed some SonarCloud issues in case of `ConfigDouble`, `ConfigString` and `ConfigSet` implementations (also in `headers/modsecurity/rules_set_properties.h`)
* in top of `headers/modsecurity/rules_set_properties.h` I had to add undefining macro directives if the target is `WIN32`, because the CI workflow was unsuccessful on Windows, because - probably - `min` and `max` are Windows C++ macros

**How does it work**
The most important part is the new `parse()` method. This decides what integer type is used in the derived class (signed/unsigned), and uses the necessary function (`stoll()` / `stoull()`). Then it checks that the conversion was success with the biggest sized integer. If not, then the `errno` will be `1` and the value will be the max/min value of used type (`int64_t` / `uin64_t`). There is another check: does the parsed value fit into the chosen type (eg. `int32_t`). If any condition matches, then the method returns with false at startup time.

## why

The problem with current solution is that the type of these variables are `ConfigDouble`, see the [variable declarations](https://github.com/owasp-modsecurity/ModSecurity/blob/cf24aeaeadefd758d0220e485bd8e312945f06df/headers/modsecurity/rules_set_properties.h#L507-L511) and their [type implementation](https://github.com/owasp-modsecurity/ModSecurity/blob/cf24aeaeadefd758d0220e485bd8e312945f06df/headers/modsecurity/rules_set_properties.h#L93).

A quick review of current implementation:
* the type of variables were double before this patch - this makes no sense, there is no 1234.6 bytes...
* the type of variables were signed - also makes sense, there is no negative value
* the parser converted the read value with `atoi()`, which gives an integer with different bitsize

Therefore if a user gave an extra high value, then the `atoi()` converted it into a negative value.

Previously I sent another PR (#3419), but I realized that solution wasn't complete. In this PR I reworked the whole storage implementation. Then I sent a new one (#3420), but there I continued to use `int` and `unsigned long` types, but I realized those are not the same on different platforms (amd64 vs i386). In this PR I changed the types with fixed width types.

## references

Fixes #3352 and #3356.

### CODE REVIEW

**Comment by airween** [comment]
@jonathansmith9485, @SonNgo2211, @EsadCetiner - here is the new one, please take a review this.

**Comment by EsadCetiner** [comment]
@airween I've been testing for a day or so and so far I haven't had any issues

**Comment by airween** [comment]
> @airween I've been testing for a day or so and so far I haven't had any issues

Great news, thank you!

**Comment by theseion** [comment]
Can you elaborate on why this caused #3352 and #3356?

File: headers/modsecurity/rules_set_properties.h [hunk 1]
```diff
@@ -68,29 +78,127 @@ class Driver;
...
+    T m_value = 0;
 
-    void merge(const ConfigInt *from) {
-        if (m_set == true || from->m_set == false) {
-            return;
-        }
+    ConfigValue() = default;
+
+    void merge(const ConfigValue<T>* from) {
+        if (m_set || !from->m_set) return;
```
Comment (theseion) [inline headers/modsecurity/rules_set_properties.h]: Personally, I very much hate unbraced if bodies. It's just too easy to make mistakes.

File: headers/modsecurity/rules_set_properties.h [hunk 2]
```diff
@@ -68,29 +78,127 @@ class Driver;
...
+        }
+        catch (const std::out_of_range&) {
+            // the value is out of range, we can not handle it
+            set_error(errmsg, "Number out of range");
+            return false;
+        }
+        catch (...) { // NOSONAR
+            // we don't need to handle all exceptions, the engine's BISON parser
+            // does not allow other symbols than numbers
+            set_error(errmsg, "An unknown error occurred while parsed the value.");
```
Comment (theseion) [inline headers/modsecurity/rules_set_properties.h]:
```suggestion
            set_error(errmsg, "An unknown error occurred while parsing number.");
```

File: headers/modsecurity/rules_set_properties.h [hunk 3]
```diff
@@ -68,29 +78,127 @@ class Driver;
...
+
+    // default parser
+    bool parse(const std::string& a, std::string* errmsg = nullptr) {
+
+        // use an alias type because the template can convert both signed and unsigned int
+        using LimitSigned = std::conditional_t<std::is_signed_v<T>, std::int64_t, std::uint64_t>;
+        LimitSigned val;
+
+        // clear errno variable, wee need that later
+        errno = 0;
```
Comment (theseion) [inline headers/modsecurity/rules_set_properties.h:106]: There's only this single assignment to `errno`, which means the conditions further below will never by true when checking `errno`.

File: headers/modsecurity/rules_set_properties.h [hunk 4]
```diff
@@ -68,29 +78,127 @@ class Driver;
...
+            // does not allow other symbols than numbers
+            set_error(errmsg, "An unknown error occurred while parsed the value.");
+            return false;
+        }
+
+        if (
+            // first condition will be true if the value is bigger than int64/uint64 max value
+            // the second condition checks if the value is fit as int64/uint64, but not fit for
+            // designed type, eg. uint32; in that case the errno will be 0, but
+            // we must check the value is not bigger than the given max() at the type class
```
Comment (theseion) [inline headers/modsecurity/rules_set_properties.h]:
```suggestion
            // The first condition will be true when the value is bigger than int64/uint64 maximum value.
            // The second condition checks whether the value fits into int64/uint64, but not
            // into the designed type, e.g., uint32; in that case the errno will be 0, but
            // we must check the value is not bigger than the defined maximum of the class.
```

File: headers/modsecurity/rules_set_properties.h [hunk 5]
```diff
@@ -68,29 +78,127 @@ class Driver;
...
+};
+
+class ConfigUnsignedLong : public ConfigValue<uint64_t> {
+protected:
+    uint64_t maxValue() const override {
+        return std::numeric_limits<uint64_t>::max();
+    }
+};
 
 class ConfigDouble {
```
Comment (theseion) [inline headers/modsecurity/rules_set_properties.h]: It doesn't look like this class is used anymore. Can't w just delete it?

**Review by theseion — CHANGES_REQUESTED** [review]
Much better!

**Comment by airween** [comment]
> Can you elaborate on why this caused #3352 and #3356?

I explained in my initial comment:

>   * if you take a look at this minimum value, it can be familiar with the mentioned log message in [#3356](https://github.com/owasp-modsecurity/ModSecurity/issues/3356#issue-2959545090): `Request body excluding files is bigger than the maximum expected. Limit: -2147483648.000000`; the reason is (I write that below too) that the current implementation uses `atoi()` function, which converts a `string` to `signed int`, but if the value is bigger than the max value above, then it overflows and casts to `int`'s minimum

File: headers/modsecurity/rules_set_properties.h (hunk 1 above)
Comment (airween) [reply headers/modsecurity/rules_set_properties.h]: Fixed in 7e3c807.

File: headers/modsecurity/rules_set_properties.h (hunk 3 above)
Comment (airween) [reply headers/modsecurity/rules_set_properties.h:106]: No, `error` is not a local variable, it's used by globally. Here [stoll()](https://github.com/owasp-modsecurity/ModSecurity/blob/9a8ce8b5f5753144b2bce003d54c6a5c0d8e6f22/headers/modsecurity/rules_set_properties.h#L108) and/or [stoull](https://github.com/owasp-modsecurity/ModSecurity/blob/9a8ce8b5f5753144b2bce003d54c6a5c0d8e6f22/headers/modsecurity/rules_set_properties.h#L110) set this variable, if any error occurred.

Please take a look at their [reference](https://en.cppreference.com/w/cpp/string/basic_string/stol#Exceptions):

> * [std::out_of_range](https://en.cppreference.com/w/cpp/error/out_of_range.html) if the converted value would fall out of the range of the result type or if the underlying function ([std::strtol](https://en.cppreference.com/w/cpp/string/byte/strtol.html) or [std::strtoll](https://en.cppreference.com/w/cpp/string/byte/strtol.html)) sets [errno](https://en.cppreference.com/w/cpp/error/errno.html) to [ERANGE](https://en.cppreference.com/w/cpp/error/errno_macros.html).

File: headers/modsecurity/rules_set_properties.h (hunk 1 above)
Comment (airween) [reply headers/modsecurity/rules_set_properties.h]: Btw: you're right, I usually try to avoid these syntax in code.

I think we should create a syntax convention and a new job in GH workflow to avoid these syntax.

File: headers/modsecurity/rules_set_properties.h (hunk 5 above)
Comment (airween) [reply headers/modsecurity/rules_set_properties.h]: I was thinking that I remove that, but I kept that because if we needed that by any reason, we can use it again.

Well, Git will remember this class - only we need to remember :smiley:.

Comment (airween) [reply headers/modsecurity/rules_set_properties.h]: Removed in abed778.

**Review by theseion — APPROVED** [review]

File: headers/modsecurity/rules_set_properties.h [hunk 6]
```diff
@@ -68,46 +78,130 @@ class Driver;
...
+
+protected:
+    // derived classes must implement the maxValue
+    virtual T maxValue() const = 0;
+    // minValue is optional
+    virtual T minValue() const { return 0; }
+
+private:
+    static inline void set_error(std::string* err, const char* msg) {
+        if (err) *err = msg;
```
Comment (theseion) [inline headers/modsecurity/rules_set_properties.h]:
```suggestion
        if (err) {
            *err = msg;
        }
```

**Review by theseion — CHANGES_REQUESTED** [review]

**Review by theseion — APPROVED** [review]
